services:
  database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: examinis_db
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always

  api:
    image: examinis_api
    entrypoint: ./entrypoint.sh
    build: .
    volumes:
      - .:/app
      - ./uploaded_images:/app/uploaded_images
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg://admin:secret@database:5432/examinis_db
    restart: always

volumes:
  pgdata:
