services:
  database:
    image: postgres
    container_name: examinis_db
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: examinis_db
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always
    networks:
      - default
      - examinis_network
  
  api:
    image: examinis_api
    container_name: examinis_api
    entrypoint: ./entrypoint.sh
    build: .
    volumes:
      - .:/app
      - ./uploads:/app/uploads
    ports:
      - "8000:8000"
    depends_on:
      - database
    environment:
      DATABASE_URL: postgresql+psycopg://admin:secret@database:5432/examinis_db
    restart: always
    networks:
      - default
      - examinis_network

volumes:
  pgdata:

networks:
  default:
  examinis_network:
    name: examinis_network