services:
  examinis_database:
    image: postgres
    container_name: examinis_database
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    restart: always

  examinis_app:
    image: examinis_app
    container_name: examinis_app
    entrypoint: ./entrypoint.sh
    build: .
    volumes:
      - .:/app
      - ./uploaded_images:/app/uploaded_images
    ports:
      - "8000:8000"
    depends_on:
      - examinis_database
    environment:
      DATABASE_URL: postgresql+psycopg://admin:secret@examinis_database:5432/app_db
    restart: always

volumes:
  pgdata:
