services:
  examinis_database:
    image: postgres:17.2-alpine3.21
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"

  examinis_app:
    image: examinis_app
    entrypoint: ./entrypoint.sh
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - examinis_database
    environment:
      DATABASE_URL: postgresql+psycopg://app_user:app_password@examinis_database:5432/app_db

volumes:
  pgdata: