"""add_question_image

Revision ID: 1dd8ff12e8da
Revises: 648bb3eea262
Create Date: 2025-02-08 13:55:30.003570

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dd8ff12e8da'
down_revision: Union[str, None] = '648bb3eea262'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('image_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('question', 'image_path')
    # ### end Alembic commands ###
