"""remove_correct_options_table

Revision ID: 88dfb220535d
Revises: 7889beed0189
Create Date: 2025-03-18 18:49:44.951244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '88dfb220535d'
down_revision: Union[str, None] = '7889beed0189'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('correct_option')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correct_option',
    sa.Column('question_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('option_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['option_id'], ['option.id'], name='correct_option_option_id_fkey'),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], name='correct_option_question_id_fkey'),
    sa.PrimaryKeyConstraint('question_id', 'option_id', name='correct_option_pkey')
    )
    # ### end Alembic commands ###
